apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deployment-2
  labels:
    app: hello-app-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-app-2
  template:
    metadata:
      labels:
        app: hello-app-2
    spec:
      containers:
      - name: hello-app
        image: abdul7235/hello-app
        ports:
        - containerPort: 8000
        envFrom:
          - configMapRef:
              name: mongo-configmap


---
apiVersion: v1
kind: Service
metadata:
  name: hello-app-nodeport
spec:
  selector:
    app: hello-app-2   
  type: NodePort
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
    nodePort: 30001

