apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deployment-1
  labels:
    app: hello-app-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-app-1
  template:
    metadata:
      labels:
        app: hello-app-1
    spec:
      containers:
      - name: hello-app
        image: abdul7235/hello-app
        ports:
        - containerPort: 8000
        envFrom:
          - configMapRef:
              name: mongo-configmap


---
apiVersion: v1
kind: Service
metadata:
  name: hello-app-loadbalancer
spec:
  selector:
    app: hello-app-1   
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
    nodePort: 30000

